DELETE http://localhost:3003/api/blogs/6460cb1a3556c8e7a343eca2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjQ1ZjljNDUxYzZhZTFmZDk5YTYxY2FiIiwiaWF0IjoxNjg0MjI4NzM2LCJleHAiOjE2ODQyMzIzMzZ9.Ts46BUsjMUzVxtIFkhNJNCIQz33MZEY-VCBSzCP7vd8