DELETE http://localhost:3003/api/blogs/646359243b47a11835694575
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NWY5YzFiMWM2YWUxZmQ5OWE2MWNhNyIsImlhdCI6MTY4NDIzMzM2NSwiZXhwIjoxNjg0MjM2OTY1fQ.2MoJG6knjg1IRcUkDlQLLSImCmQ3KPh75HjSH9jV9k0