
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Some Blog3",
  "author": "Some Author",
  "url": "Some URL",
  "likes": 5,
  "userId": "645f9c1b1c6ae1fd99a61ca7"
}

### 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Some Blog2",
  "author": "Some Author",
  "url": "Some URL",
  "likes": 5
}