
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NWY5YzFiMWM2YWUxZmQ5OWE2MWNhNyIsImlhdCI6MTY4NDIzMDI2NiwiZXhwIjoxNjg0MjMzODY2fQ.n7IHL3Nntn3qB4oyByLkF-39PEwZJ0nPy8sL-L_nhNA

{
  "title": "Some Blog7",
  "author": "Some Author",
  "url": "Some URL",
  "likes": 5,
  "userId": "645f9c1b1c6ae1fd99a61ca7"
}

### 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Some Blog2",
  "author": "Some Author",
  "url": "Some URL",
  "likes": 5
}