
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNjQ1ZjljNDUxYzZhZTFmZDk5YTYxY2FiIiwiaWF0IjoxNjg0MzI1OTc3LCJleHAiOjE2ODQzMjk1Nzd9.69hUkWVeWE0iXlBmZbKJ72lkamq9tcofnwspcQs-bVg

{
  "title": "Some Blog7",
  "author": "Some Author",
  "url": "Some URL",
  "likes": 5,
  "userId": "645f9c1b1c6ae1fd99a61ca7"
}

### 
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Some Blog2",
  "author": "Some Author",
  "url": "Some URL",
  "likes": 5
}